pipeline{
    environment {     
    ssh_vm= credentials('local_ssh')     
    }
    agent {
        label 'deploy'
        }
    stages{
        stage("Pull Docker-Image") {
            steps{
                script{
                sh 'ssh -tto StrictHostKeyChecking=no debian@localhost -p 22022 ./deploy.sh'
                }
            }
        }
        stage("Start container"){
            steps{
                script {
                    sh 'ssh -tto StrictHostKeyChecking=no debian@localhost -p 22022 "docker run --publish 8080:8080 -d pato98/acdc_presentation"'
                }
            }
        }
    }
}