pipeline{
    environment {     
    ssh_vm= credentials('local_ssh')     
    }
    agent {
        label 'deploy'
        }
    stages{
        stage("Pull Docker-Image") {
            steps{
                script{
                sh 'ssh -tto StrictHostKeyChecking=no debian@localhost -p 22022 ./deploy.sh'
                }
            }
        }
        stage("Start container"){
            steps{
                script {
                    sh 'ssh -tto StrictHostKeyChecking=no debian@localhost -p 22022 "docker run --name acdc --publish 8080:8080 -d pato98/acdc_presentation && docker run --name db --publish 3308:3306 -d pato98/acdc_db_presentation"'
                }
            }
        }
        stage("Connect both containers via network"){
            steps{
                script{
                    sh 'ssh -tto StrictHostKeyChecking=no debian@localhost -p 22022 "docker network create acdc_lamp && docker network connect acdc_lamp acdc && docker network connect db"'
                }
            }
        }
    }
}