version: '3'
services:
  webserver:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.Prod
      tags:
        - "pato98/acdc_presentation"
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    ports:
      - 8081:80
      - 9000:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - acdc_lamp

  db:
    build:
      context: .
      dockerfile: Dockerfile.MySQL
      tags:
        - "pato98/acdc_db_presentation"
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: ACDC_LAMP
      MYSQL_USER: admin
      MYSQL_PASSWORD: adm1n
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - acdc_lamp

networks:
  acdc_lamp:

    
