version: '3'
services:
  webserver:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "../"
        target: /var/www
        bind:
          propagation: rshared
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    ports:
      - 8081:80
      - 9000:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - acdc_lamp

  db:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: ACDC_LAMP
      MYSQL_USER: admin
      MYSQL_PASSWORD: adm1n
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ../data/:/docker-entrypoint-initdb.d
    networks:
      - acdc_lamp

networks:
  acdc_lamp:
    driver: bridge
    
