FROM shinsenter/laminas:php8.2 as application

#============================================================

ENV PUID=1343
ENV PGID=1343

ENV WEBHOME ="/var/www/html"

#============================================================



