services:
  #nginx
  webserver:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"

    volumes:
      - .././nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laminas

      #php
  app:
    build:
      dockerfile: .././php/Dockerfile
      target: "${BUILD_TARGET:-app}"

    volumes:
      - .././app:/var/www/html
      - .././php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      XDEBUG_MODE: off
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - laminas
  #MySQL
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql

    ports:
      - "3307:3306"
    expose:
      - 3307

    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - laminas
  #redis
  cache:
    image: redis:latest
    networks:
      - laminas


volumes:
  mysqldata:

networks:
  laminas:
