pipeline{
    agent any
    stages{
        stage("Verify tooling") {
            steps {
                sh '''
                    docker info
                    docker version
                    docker compose version
                    '''
            }
        }
        stage("Prune Docker data"){
            steps{
                sh 'docker system prune -a --volumes -f'
            }

        }
        stage("Build docker image") {
            steps {
                dir(docker){
                sh 'docker compose up -d --wait'
                sh 'docker compose ps'
                }
            }
        }
    }
    post {
        always {
            sh 'docker compose down --remove-orphans -v'
            sh 'docker compose ps'
        }
    }
}
