pipeline{
    agent any
    stages{
        stage("Verify tooling") {
            steps {
                sh '''
                    docker info
                    docker version
                    docker compose version
                    '''
            }
        }
        stage("Build docker image") {
            steps {
                sh 'cd /docker'
                sh 'docker-compose up --build'
            }
        }
    }
    post {
        always {
            sh 'docker compose down --remove-orphans -v'
            sh 'docker compose ps'
        }
    }
}
